services:
  - type: web
    name: dentsu-xmd-v7
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: SESSION_ID
        sync: false
      - key: SESSION_2
        sync: false
      - key: AUTOREAD_ENABLED
        value: "false"
      - key: AUTOTYPING_ENABLED
        value: "false"
      - key: AUTORECORD_ENABLED
        value: "false"
      - key: AUTOLIKE_ENABLED
        value: "false"
      - key: DASHBOARD_PORT
        value: "10000"
      - key: PORT
        value: "10000"
